### ISSUE TITLE
strange result in Curvedemo2.Py

### ISSUE THREAD

**Issue by stonebig** [PierreRaybaut/PythonQwt#22]
no wheel on pypi for 0.1.1... but winpython compiles it ... let me try

**Comment by stonebig** [comment]
I get one strange result in Curvedemo2.py
![guiqwt_curvedemo2](https://cloud.githubusercontent.com/assets/4312421/9838508/4a2985f2-5a5f-11e5-8cbb-c90c0b079803.GIF)

**Comment by PierreRaybaut** [comment]
That is a known bug, see line 9:
https://github.com/PierreRaybaut/python-qwt/blob/master/qwt/tests/CurveDemo2.py#L9

**Comment by PierreRaybaut** [comment]
Regarding the wheel package: there is no wheel indeed, but you may ignore this release as it fixes only a bug happening when building on non-Windows platforms.

**Comment by stonebig** [comment]
from 0.2..0 of today:
- thank you for the wheel,
- still the issue in curvedemo2.py but all the rest looks ok.

**Comment by stonebig** [comment]
it's still there

**Comment by PierreRaybaut** [comment]
I know... but as long as it is a v0.X, I think I won't take a look at this example which is absolutely not representative of PythonQwt API state I think.

**Comment by stonebig** [comment]
wouldn't it be preferable to remove this test, so ? at least for now.

**Comment by stonebig** [comment]
great !
![qwt_curvedemo2_rocks](https://cloud.githubusercontent.com/assets/4312421/11021105/cba4a8e2-8637-11e5-8a28-dc97c58c4a9f.GIF)
