### ISSUE TITLE
is this result of CPUplot.py the desired one ?

### ISSUE THREAD

**Issue by stonebig** [PierreRaybaut/PythonQwt#27]
the graphic looks odd to me, but maybe it's the intended one:

![pythonqwt_cpu_usage](https://cloud.githubusercontent.com/assets/4312421/11016221/ae3a4fcc-857a-11e5-976b-b13c9f7269ef.GIF)

**Comment by PierreRaybaut** [comment]
The result should be the following:
![cpu1](https://cloud.githubusercontent.com/assets/1311787/11016810/1e3e0c62-858c-11e5-878f-b107894b4e7b.png)

But there was a bug with curve shading (see Issue #28), and now it should look like this:
![cpu2](https://cloud.githubusercontent.com/assets/1311787/11016834/ac7700ba-858c-11e5-984c-7dc294968258.png)

**Comment by PierreRaybaut** [comment]
Did you crop your screenshot? Because there should be labels on axes and ticks in both X-axis and Y-axis.

**Comment by stonebig** [comment]
Yes, I just picked the part that was bothering me. the rest was looking normal
