### ISSUE TITLE
Add support for stacked area plots

### ISSUE THREAD

**Issue by estan** [PierreRaybaut/PythonQwt#32]
It would be great to have an API for working with "stacked" area plots. A stacked area plot is a collection of line plots where the the values on the y axis are accumulated at each x position, and the resulting areas between lines are filled. These are useful if you, for example, want to illustrate the composition of something as a set of percentages over time.

It's currently possible to simulate a stacked area plot by preprocessing your data and doing the accumulation yourself, and use a set of `QwtPlotCurve` drawn on top of each other. But it would be very nice if there was a dedicated API for this (`QwtPlotAreaStack`, or `QwtPlotStack`, ...?) that could take care of those details.

I understand this is quite a big feature request, but I'm interested in what you think.

**Comment by PierreRaybaut** [comment]
That would be a feature to add to a higher-level library, e.g. in [guiqwt](https://github.com/PierreRaybaut/guiqwt) or its future replacement [plotpy](https://github.com/Codra-Ingenierie-Informatique/plotpy).
