### ISSUE TITLE
Tick drawing artifact when setting all plot margins to 0

### ISSUE THREAD

**Issue by estan** [PierreRaybaut/PythonQwt#35]
I'm working with the left and top axes enabled. The look I'm getting is:

![example](https://cloud.githubusercontent.com/assets/86675/13635653/8b1e953c-e5fd-11e5-866b-38b3786d1443.png)

How can I make the Y axis positioned at X = 0, and the X axis at Y = 0, so that they meet precisely at the origin? E.g. I'd like the axes to look roughly like this:

![ex](https://cloud.githubusercontent.com/assets/86675/13635744/147fa000-e5fe-11e5-9e02-dbc4a85afe7b.png)

**Comment by estan** [comment]
I've tried getting the scale draw of the axes and move()ing it to 0,0, but it seems to have no effect.

**Comment by estan** [comment]
Sorry, the image above is slightly misrepresentative as I haven't flipped my Y axis yet. It was meant to show the Y axis going from 0 at the top to 1000 at the bottom (how do I do that btw?). My general question is how to position the Y axis at a precise X value, and the X axis at a precise Y value.

**Comment by estan** [comment]
It seems `plotLayout().setAlignCanvasToScales(True)` will get me halfway there: There's no longer any space between my curve and the end of the canvas, but there's still a gap between the canvas and the axes backbones.

**Comment by estan** [comment]
Alright, this seems to do the trick:

```python
        self.plotLayout().setCanvasMargin(0)
        self.axisWidget(QwtPlot.yLeft).setMargin(0)
        self.axisWidget(QwtPlot.xTop).setMargin(0)
```

Result:

![almost](https://cloud.githubusercontent.com/assets/86675/13636310/93d9fe10-e601-11e5-9c7a-1d6a40486023.png)

But as you can see there's some painting artifact at the first major mark of the X axis. Any idea what's going on here?

**Comment by PierreRaybaut** [comment]
This is apparently a rounding error of some kind, within the code handling the plot layout ([here](https://github.com/PierreRaybaut/PythonQwt/blob/master/qwt/plot_layout.py#L694) and/or [there](https://github.com/PierreRaybaut/PythonQwt/blob/master/qwt/plot_layout.py#L787), or maybe also [here](https://github.com/PierreRaybaut/PythonQwt/blob/master/qwt/plot_layout.py#L921)).

The render result when setting all margins to 0 is not the same in PythonQwt as in Qwt original C++ library, so there maybe something to dig in the code parts cited above.

This might take some time but it's not hopeless as it works in the original C++ code.

**Comment by PierreRaybaut** [comment]
As a note for myself:
  * This is bug is probably related to a rounding error in [QwtPlotLayout](https://github.com/PierreRaybaut/PythonQwt/blob/master/qwt/plot_layout.py)
  * This bug is not happening with ``PyQwt5`` (see screenshots below), so maybe it's working with the original Qwt 6 C++ code and something was lost when porting the code in Python.
  * However, let's remember that ``PythonQwt`` is based on Qwt 6 whereas ``PyQwt`` is based on Qwt 5: in Qwt v6, all widget coordinates are using floating point values (``QPointF``, ``QRectF``, ...) instead of integer values like version 5 (``QPoint``, ``QRect``, ...).

Here are two screenshots produced by the newly introduced ["plot without margins" test](https://github.com/PierreRaybaut/PythonQwt/blob/master/qwt/tests/no_margin.py):

``PyQwt`` | ``PythonQwt``
------------ | ----------------
Qwt 5 | Qwt 6
![no_margin-pyqwt](https://cloud.githubusercontent.com/assets/1311787/13669677/4f7a1934-e6c5-11e5-9662-db9e80198b65.png) | ![no_margin-pythonqwt](https://cloud.githubusercontent.com/assets/1311787/13669688/59014fae-e6c5-11e5-909d-a2acd990c98e.png)

**Comment by estan** [comment]
Thanks a lot for looking into this. I made a small Qwt6 C++ test:

```cpp
#include <cmath>

#include <QApplication>
#include <QFrame>
#include <QWidget>

#include <qwt_plot.h>
#include <qwt_plot_curve.h>
#include <qwt_plot_layout.h>
#include <qwt_point_data.h>
#include <qwt_scale_widget.h>


class FunctionData : public QwtSyntheticPointData
{
public:
    FunctionData(double (*y)(double)) : QwtSyntheticPointData(500), d_y(y) { }

    virtual double y(double x) const {
        return d_y(x);
    }

private:
    double (*d_y)(double);
};


class TestPlot : public QwtPlot
{
    Q_OBJECT
public:
    TestPlot(QWidget *parent = 0) : QwtPlot(parent) {
        setWindowTitle("Qwt");
        enableAxis(QwtPlot::xTop, true);
        enableAxis(QwtPlot::yRight, true);

        setAxisScale(QwtPlot::xTop, 0, 10);
        setAxisScale(QwtPlot::xBottom, 0, 10);
        setAxisScale(QwtPlot::yRight, -1, 1);
        setAxisScale(QwtPlot::yLeft, -1, 1);

        QwtPlotCurve *curve1 = new QwtPlotCurve("Test Curve 1");
        curve1->setData(new FunctionData(::sin));
        curve1->attach(this);

        qobject_cast<QFrame*>(canvas())->setFrameStyle(QFrame::NoFrame);
        plotLayout()->setCanvasMargin(0);
        axisWidget(QwtPlot::yLeft)->setMargin(0);
        axisWidget(QwtPlot::xTop)->setMargin(0);
        axisWidget(QwtPlot::yRight)->setMargin(0);
        axisWidget(QwtPlot::xBottom)->setMargin(0);
    }
};

int main(int argc, char *argv[]) {
    QApplication app(argc, argv);

    TestPlot plot;
    plot.resize(800, 600);
    plot.show();

    return app.exec();
}

#include "moc_qwttest.cpp"
```

```
TEMPLATE = app
CONFIG += qwt
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qwttest.cpp
HEADERS += qwttest.cpp
```

Result:

![qwt6](https://cloud.githubusercontent.com/assets/86675/13673051/ac0239fe-e6d7-11e5-907b-066d3d19c091.png)

**Comment by estan** [comment]
I can also note: At the moment I'm just doing `self.plotLayout().setAlignCanvasToScales(True)` and setting the margin of the scale widgets to 0, not setting the canvas margin to 0 (to avoid the artifact on the tick mark). This gets me almost the look I want. But the curves are still being "cut off" when touching the axis (as seen in both my example and yours), so would love to have this fixed.

**Comment by estan** [comment]
@PierreRaybaut: I made a small find:

From [qwt_scale_widget.cpp](https://sourceforge.net/p/qwt/code/HEAD/tree/trunk/qwt/src/qwt_scale_widget.cpp), in `QwtScaleWidget::layoutScale`:

```cpp
const QRectF r = contentsRect();
```

So it will work with a `QRectF` in the subsequent calculations, but in the corresponding `PythonQwt` code:

```python
r = self.contentsRect()
```

So it will work with a `QRect`.

Could the problem be somewhere around here?

**Comment by estan** [comment]
I gave it a try, changing it to `r = QRectF(self.contentsRect())`, but no cigar, not that easy :)

**Comment by PierreRaybaut** [comment]
Yesterday, I took the time to compare [qwt_plot_layout.cpp](https://sourceforge.net/p/qwt/code/HEAD/tree/trunk/qwt/src/qwt_plot_layout.cpp) and [plot_layout.py](https://github.com/PierreRaybaut/PythonQwt/blob/master/qwt/plot_layout.py)... no luck: everything seems fine.

**Comment by PierreRaybaut** [comment]
Still investigating, from time to time... but it's like finding a needle in a haystack!

**Comment by estan** [comment]
Yea, I can imagine :) Wish I had more time to help at the moment. It's no hurry.

I guess it's a matter of going through all related code looking for variables/return values/parameters that *should* be float or *should* be int and add assertions of their type.

**Comment by JAE-UH** [comment]
I suspect the bug is around [here, somewhere.](https://github.com/PierreRaybaut/PythonQwt/blob/72fd6d07435dd5ba62f0ccd9de4bed187034c82a/qwt/plot_layout.py#L810)

It specifically messes with the yLeft axis and alignCanvasToScales.

I just can't find it yet.

**Comment by PierreRaybaut** [comment]
4 years later... nailed it ;-)

**Comment by estan** [comment]
👌
