### ISSUE TITLE
Inverting the Y axis?

### ISSUE THREAD

**Issue by estan** [PierreRaybaut/PythonQwt#36]
How can I invert the Y axis of a `QwtPlot`? I have a plot like this:

![almost](https://cloud.githubusercontent.com/assets/86675/13636365/e0b40c30-e601-11e5-9a7a-fc53aff93d2c.png)

But I would like the Y scale to go from 0 at the top to 1000 at the bottom, since it represents the depth of a bore hole. Must I manually construct a `QwtScaleDiv` and set the axis scale div?

**Comment by PierreRaybaut** [comment]
No, just use the ``setAxisScale`` method and invert the min and max values:
http://pythonhosted.org/PythonQwt/reference/plot.html#qwt.plot.QwtPlot.setAxisScale

See for example the ``set_axis_direction`` implementation in ``guiqwt``:
https://github.com/PierreRaybaut/guiqwt/blob/6e3e2c66f9d353dcf2fd1d872439444545d37a08/guiqwt/curve.py#L1681

**Comment by estan** [comment]
Aha. Of course. Thanks!

At the moment I was working with auto-scaled axes, but since I need to be explicit with the axes anyway in the end (to support scrolling/zooming), it's no problem that I have to set the scale explicitly to invert it.
