### ISSUE TITLE
Add support for bar charts

### ISSUE THREAD

**Issue by estan** [PierreRaybaut/PythonQwt#38]
It would be great if PythonQwt had support for bar charts.

Is it in general planned to port/implement more of the plot items that Qwt offers?

**Comment by estan** [comment]
Are the plot types for which `Rtti_*` enum values have been reserved in `plot.py` the ones that are planned maybe?

**Comment by PierreRaybaut** [comment]
There is currently no plan to add more plot types as [guiqwt](https://github.com/PierreRaybaut/guiqwt) (or the forthcoming fork [plotpy](https://pypi.org/project/plotpy/)) add much more high-level features than Qwt.
