### ISSUE TITLE
Funcionality for plotting dates or timeseries?

### ISSUE THREAD

**Issue by titusjan** [PierreRaybaut/PythonQwt#44]
First of all thanks for making this library. 

Is it somehow possible to make line plots where the x-coordinates are Python datetime objects or Numpy datetime64 elements? 

I couldn't find anything in the documentation or source. I'm not familiar with Qwt but it seems to have a [QwtDate class](http://qwt.sourceforge.net/class_qwt_date.html). However this is apparently not ported to PythonQwt.

Any help would be appreciated.

**Comment by twillis449** [comment]
Have a look at the demo programs CPUplot.py and DataDemo.py in the subdirectory qwt/tests. They could provably be adapted to do what you want.
