### ISSUE TITLE
Actually NAME the library QwtMathMLTextEngine is provided by

### ISSUE THREAD

**Issue by Kaladrius** [PierreRaybaut/PythonQwt#73]
According to the documentation (https://pythonqwt.readthedocs.io/en/latest/reference/text.html#qwttextengine) the **QwtMathMLTextEngine** is built into a separate library due to licensing. Sadly no information is given as to what library it is supposedly a part of...
Has this engine been implemented anywhere? If it does, please mention the corresponding library! Otherwise please change the documentation to reflect that. (Like you have with the Latex engine)

I am trying to render a complex function using either Latex or MathML. As per your documentation no latex engine is implemented yet, while a MathML engine apparently exists somewhere, though even after multiple hours of searching I cannot find any python library that provides a MathML render engine that PythonQwt accepts...

**Comment by PierreRaybaut** [comment]
Actually MathML text engine is not supported by ``PythonQwt`` (this part of the documentation was a residue from Qwt documentation).
